language: cpp
os: linux
dist: xenial
env: WORKSPACE=$TRAVIS_BUILD_DIR
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libcurl4-openssl-dev 
    - libboost-all-dev
    - libboost-dev
    - clang
matrix:
  include:
  - compiler: clang
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using clang 
    script: $WORKSPACE/scripts/linux/build.sh
  - compiler: gcc
    env: BUILD_TYPE=COVERAGE WORKSPACE=$TRAVIS_BUILD_DIR
    name: Linux Build using gcc & tests & code coverage
    script: $WORKSPACE/scripts/linux/build.sh && $WORKSPACE/scripts/linux/test.sh
  - language: android
    dist: xenial
    jdk: oraclejdk8
    name: Android Build
    android:
      components:
      - tools
      - platform-tools
      - build-tools-28.0.3
      - android-28
      - extra-google-m2repository
      - extra-android-m2repository # for design library
      licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
    addons:
      apt:
        packages: cmake
    install:
    - echo y | sdkmanager 'cmake;3.6.4111459'
    before_script:
    - wget https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip
    - wget https://dl.google.com/android/repository/platform-28_r06.zip
    - unzip -qq android-ndk-r20-linux-x86_64.zip
    - unzip -qq platform-28_r06.zip
    - export SDK_ROOT="$TRAVIS_BUILD_DIR/android-9"
    - export ANDROID_NDK_HOME="$TRAVIS_BUILD_DIR/android-ndk-r20"
    script: $WORKSPACE/scripts/android/build.sh
  - os: osx
    name: OSX Build
    env: BUILD_TYPE=RelWithDebInfo WORKSPACE=$TRAVIS_BUILD_DIR
    script: $WORKSPACE/scripts/linux/build.sh
  - os: osx
    name: IOS Build
    script: $WORKSPACE/scripts/ios/build.sh  
branches:
  only:
  - master
