trigger:
- master
pr:
- master
schedules:
- cron: "0 0 * * *"
  displayName: Nightly build. Build ios on MacOS.
  branches:
    include:
    - master

pool:
  vmImage: 'macOS-10.14'
variables:
  BUILD_TYPE: RelWithDebInfo
steps:
- script: bash -x scripts/ios/build.sh
  displayName: 'Build ios on MacOS Stage'
